name: QuicktestPRAgainstDev

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]


jobs:

  test:
    name: Run quicktest on PR branch
    runs-on: ubuntu-16.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: DockerRunQuicktest
        run: |
          docker build -t finn_base_gha -f docker/Dockerfile .
          docker run --rm -v $(pwd):/workspace/finn-base finn_base_gha
